// Server-side allowlist of India's 36 regions (28 states + 8 UTs).
// Mirrors content/regions.js in the frontend repo. Only ids from this map
// may reach the AI prompt — the region param is user input.

export const REGION_LABELS = {
  "andhra-pradesh":    "Andhra Pradesh",
  "arunachal-pradesh": "Arunachal Pradesh",
  "assam":             "Assam",
  "bihar":             "Bihar",
  "chhattisgarh":      "Chhattisgarh",
  "goa":               "Goa",
  "gujarat":           "Gujarat",
  "haryana":           "Haryana",
  "himachal-pradesh":  "Himachal Pradesh",
  "jharkhand":         "Jharkhand",
  "karnataka":         "Karnataka",
  "kerala":            "Kerala",
  "madhya-pradesh":    "Madhya Pradesh",
  "maharashtra":       "Maharashtra",
  "manipur":           "Manipur",
  "meghalaya":         "Meghalaya",
  "mizoram":           "Mizoram",
  "nagaland":          "Nagaland",
  "odisha":            "Odisha",
  "punjab":            "Punjab",
  "rajasthan":         "Rajasthan",
  "sikkim":            "Sikkim",
  "tamil-nadu":        "Tamil Nadu",
  "telangana":         "Telangana",
  "tripura":           "Tripura",
  "uttar-pradesh":     "Uttar Pradesh",
  "uttarakhand":       "Uttarakhand",
  "west-bengal":       "West Bengal",
  "andaman-nicobar":   "Andaman & Nicobar Islands",
  "chandigarh":        "Chandigarh",
  "dnh-daman-diu":     "Dadra & Nagar Haveli and Daman & Diu",
  "delhi":             "Delhi",
  "jammu-kashmir":     "Jammu & Kashmir",
  "ladakh":            "Ladakh",
  "lakshadweep":       "Lakshadweep",
  "puducherry":        "Puducherry",
};
